//
//  NSString+FontAwesome.h
//
//  Copyright (c) 2012 Alex Usbergo. All rights reserved.
//
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//

#import <Foundation/Foundation.h>

static NSString *const kFontAwesomeFamilyName = @"FontAwesome";

typedef NS_ENUM(NSInteger, AU_FAIcon) {
    AU_FAIconGlass = 0,
    AU_FAIconMusic,
    AU_FAIconSearch,
    AU_FAIconEnvelope,
    AU_FAIconHeart,
    AU_FAIconStar,
    AU_FAIconStarEmpty,
    AU_FAIconUser,
    AU_FAIconFilm,
    AU_FAIconThLarge,
    AU_FAIconTh,
    AU_FAIconThList,
    AU_FAIconOk,
    AU_FAIconRemove,
    AU_FAIconZoomIn,
    AU_FAIconZoomOut,
    AU_FAIconOff,
    AU_FAIconSignal,
    AU_FAIconCog,
    AU_FAIconTrash,
    AU_FAIconHome,
    AU_FAIconFile,
    AU_FAIconTime,
    AU_FAIconRoad,
    AU_FAIconDownloadAlt,
    AU_FAIconDownload,
    AU_FAIconUpload,
    AU_FAIconInbox,
    AU_FAIconPlayCircle,
    AU_FAIconRepeat,
    AU_FAIconRefresh,
    AU_FAIconListAlt,
    AU_FAIconLock,
    AU_FAIconFlag,
    AU_FAIconHeadphones,
    AU_FAIconVolumeOff,
    AU_FAIconVolumeDown,
    AU_FAIconVolumeUp,
    AU_FAIconQrcode,
    AU_FAIconBarcode,
    AU_FAIconTag,
    AU_FAIconTags,
    AU_FAIconBook,
    AU_FAIconBookmark,
    AU_FAIconPrint,
    AU_FAIconCamera,
    AU_FAIconFont,
    AU_FAIconBold,
    AU_FAIconItalic,
    AU_FAIconTextHeight,
    AU_FAIconTextWidth,
    AU_FAIconAlignLeft,
    AU_FAIconAlignCenter,
    AU_FAIconAlignRight,
    AU_FAIconAlignJustify,
    AU_FAIconList,
    AU_FAIconIndentLeft,
    AU_FAIconIndentRight,
    AU_FAIconFacetimeVideo,
    AU_FAIconPicture,
    AU_FAIconPencil,
    AU_FAIconMapMarker,
    AU_FAIconAdjust,
    AU_FAIconTint,
    AU_FAIconEdit,
    AU_FAIconShare,
    AU_FAIconCheck,
    AU_FAIconMove,
    AU_FAIconStepBackward,
    AU_FAIconFastBackward,
    AU_FAIconBackward,
    AU_FAIconPlay,
    AU_FAIconPause,
    AU_FAIconStop,
    AU_FAIconForward,
    AU_FAIconFastForward,
    AU_FAIconStepForward,
    AU_FAIconEject,
    AU_FAIconChevronLeft,
    AU_FAIconChevronRight,
    AU_FAIconPlusSign,
    AU_FAIconMinusSign,
    AU_FAIconRemoveSign,
    AU_FAIconOkSign,
    AU_FAIconQuestionSign,
    AU_FAIconInfoSign,
    AU_FAIconScreenshot,
    AU_FAIconRemoveCircle,
    AU_FAIconOkCircle,
    AU_FAIconBanCircle,
    AU_FAIconArrowLeft,
    AU_FAIconArrowRight,
    AU_FAIconArrowUp,
    AU_FAIconArrowDown,
    AU_FAIconShareAlt,
    AU_FAIconResizeFull,
    AU_FAIconResizeSmall,
    AU_FAIconPlus,
    AU_FAIconMinus,
    AU_FAIconAsterisk,
    AU_FAIconExclamationSign,
    AU_FAIconGift,
    AU_FAIconLeaf,
    AU_FAIconFire,
    AU_FAIconEyeOpen,
    AU_FAIconEyeClose,
    AU_FAIconWarningSign,
    AU_FAIconPlane,
    AU_FAIconCalendar,
    AU_FAIconRandom,
    AU_FAIconComment,
    AU_FAIconMagnet,
    AU_FAIconChevronUp,
    AU_FAIconChevronDown,
    AU_FAIconRetweet,
    AU_FAIconShoppingCart,
    AU_FAIconFolderClose,
    AU_FAIconFolderOpen,
    AU_FAIconResizeVertical,
    AU_FAIconResizeHorizontal,
    AU_FAIconBarChart,
    AU_FAIconTwitterSign,
    AU_FAIconFacebookSign,
    AU_FAIconCameraRetro,
    AU_FAIconKey,
    AU_FAIconCogs,
    AU_FAIconComments,
    AU_FAIconThumbsUp,
    AU_FAIconThumbsDown,
    AU_FAIconStarHalf,
    AU_FAIconHeartEmpty,
    AU_FAIconSignout,
    AU_FAIconLinkedinSign,
    AU_FAIconPushpin,
    AU_FAIconExternalLink,
    AU_FAIconSignin,
    AU_FAIconTrophy,
    AU_FAIconGithubSign,
    AU_FAIconUploadAlt,
    AU_FAIconLemon,
    AU_FAIconPhone,
    AU_FAIconCheckEmpty,
    AU_FAIconBookmarkEmpty,
    AU_FAIconPhoneSign,
    AU_FAIconTwitter,
    AU_FAIconFacebook,
    AU_FAIconGithub,
    AU_FAIconUnlock,
    AU_FAIconCreditCard,
    AU_FAIconRss,
    AU_FAIconHdd,
    AU_FAIconBullhorn,
    AU_FAIconBell,
    AU_FAIconCertificate,
    AU_FAIconHandRight,
    AU_FAIconHandLeft,
    AU_FAIconHandUp,
    AU_FAIconHandDown,
    AU_FAIconCircleArrowLeft,
    AU_FAIconCircleArrowRight,
    AU_FAIconCircleArrowUp,
    AU_FAIconCircleArrowDown,
    AU_FAIconGlobe,
    AU_FAIconWrench,
    AU_FAIconTasks,
    AU_FAIconFilter,
    AU_FAIconBriefcase,
    AU_FAIconFullscreen,
    AU_FAIconGroup,
    AU_FAIconLink,
    AU_FAIconCloud,
    AU_FAIconBeaker,
    AU_FAIconCut,
    AU_FAIconCopy,
    AU_FAIconPaperClip,
    AU_FAIconSave,
    AU_FAIconSignBlank,
    AU_FAIconReorder,
    AU_FAIconListUl,
    AU_FAIconListOl,
    AU_FAIconStrikethrough,
    AU_FAIconUnderline,
    AU_FAIconTable,
    AU_FAIconMagic,
    AU_FAIconTruck,
    AU_FAIconPinterest,
    AU_FAIconPinterestSign,
    AU_FAIconGooglePlusSign,
    AU_FAIconGooglePlus,
    AU_FAIconMoney,
    AU_FAIconCaretDown,
    AU_FAIconCaretUp,
    AU_FAIconCaretLeft,
    AU_FAIconCaretRight,
    AU_FAIconColumns,
    AU_FAIconSort,
    AU_FAIconSortDown,
    AU_FAIconSortUp,
    AU_FAIconEnvelopeAlt,
    AU_FAIconLinkedin,
    AU_FAIconUndo,
    AU_FAIconLegal,
    AU_FAIconDashboard,
    AU_FAIconCommentAlt,
    AU_FAIconCommentsAlt,
    AU_FAIconBolt,
    AU_FAIconSitemap,
    AU_FAIconUmbrella,
    AU_FAIconPaste,
    AU_FAIconUserMd,
	AU_FAIconStethoscope,
	AU_FAIconBuilding,
	AU_FAIconHospital,
	AU_FAIconAmbulance,
	AU_FAIconMedkit,
	AU_FAIconHSign,
	AU_FAIconPlusSignAlt,
	AU_FAIconSpinner,
	AU_FAIconCloudDownload,
	AU_FAIconCloudUpload,
	AU_FAIconLightbulb,
	AU_FAIconExchange,
	AU_FAIconBellAlt,
	AU_FAIconFileAlt,
	AU_FAIconBeer,
	AU_FAIconCoffee,
	AU_FAIconFood,
	AU_FAIconFighterJet,
	AU_FAIconAngleLeft,
	AU_FAIconAngleRight,
	AU_FAIconAngleUp,
	AU_FAIconAngleDown,
	AU_FAIconDoubleAngleLeft,
	AU_FAIconDoubleAngleRight,
	AU_FAIconDoubleAngleUp,
	AU_FAIconDoubleAngleDown,
	AU_FAIconCircleBlank,
	AU_FAIconCircle,
	AU_FAIconDesktop,
	AU_FAIconLaptop,
	AU_FAIconTablet,
	AU_FAIconMobilePhone,
	AU_FAIconQuoteLeft,
	AU_FAIconQuoteRight,
	AU_FAIconReply,
	AU_FAIconGithubAlt,
	AU_FAIconFolderCloseAlt,
	AU_FAIconFolderOpenAlt,
    AU_FAIconSuitcase,
};

@interface NSString (AU_FontAwesome)

/* Returns the correct enum for a font-awesome icon.
 * The list of identifiers can be found here:
 * http://fortawesome.github.com/Font-Awesome/#all-icons */
+ (AU_FAIcon)fontAwesomeEnumForIconIdentifier:(NSString*)string;

/* Returns the font-awesome character associated to the
 * icon enum passed as argument */
+ (NSString*)fontAwesomeIconStringForEnum:(AU_FAIcon)value;

/* Returns the font-awesome character associated to the font-awesome
 * identifier.
 * http://fortawesome.github.com/Font-Awesome/#all-icons */
+ (NSString*)fontAwesomeIconStringForIconIdentifier:(NSString*)identifier;

@end
